### ISSUE TITLE
Got error when running a player

### ISSUE THREAD

**Issue by Douilol** [MCJack123/sanjuuni#20]
Can someone tell me why im getting these errors?

![image](https://github.com/MCJack123/sanjuuni/assets/106202984/f065dd82-febb-47b8-a7da-5f6ddb09dc38)

**Comment by MCJack123** [comment]
Because you didn't give them a path to a file.

**Comment by Douilol** [comment]
> Because you didn't give them a path to a file.

Yes but where i need to give it the path to the file

**Comment by MCJack123** [comment]
After the command name, like any other command: `32vid-player-mini video.32v`

**Comment by Douilol** [comment]
> After the command name, like any other command: `32vid-player-mini video.32v`

Do you know why I'm getting this error?
![image](https://github.com/MCJack123/sanjuuni/assets/106202984/37f34b2f-c43c-4693-a42a-f60ea3407103)

**Comment by MCJack123** [comment]
Your video is too big. Large files take a long time to decode and decompress, which causes CC to kill it. Reduce the resolution of the file with `-W`/`-H`, and potentially disable compression with `-c none` when encoding.

**Comment by Douilol** [comment]
> Your video is too big. Large files take a long time to decode and decompress, which causes CC to kill it. Reduce the resolution of the file with `-W`/`-H`, and potentially disable compression with `-c none` when encoding.
> 
> Alternatively, use the latest build and `32vid-player-mini`, which uses a more efficient compression scheme that decodes in real-time.

okay and is there any other way (Like Raw) to run a long movie(Big size) except your Websocket and Http?

**Comment by Douilol** [comment]
I have to say. Very impressive work you have done! And still trying to help with issues. Thank you for your hard work!
