### ISSUE TITLE
Too long without yielding (32vid-player.lua)

### ISSUE THREAD

**Issue by Commandcracker** [MCJack123/sanjuuni#5]
![image](https://user-images.githubusercontent.com/49335821/200921995-20bf579e-c281-458a-89d3-7af9ce4e9363.png)

**Comment by Commandcracker** [comment]
Is 32vid-player.lua no longer supported ?
It should work to fix it:
```
os.queueEvent("32vid_process")
os.pullEvent()
```

**Comment by MCJack123** [comment]
It already does this. Your computer's too slow.
