### ISSUE TITLE
websocket-player not working

### ISSUE THREAD

**Issue by Commandcracker** [MCJack123/sanjuuni#7]
![Screenshot_20221109_204636](https://user-images.githubusercontent.com/49335821/200926677-46c02b7b-66bf-4cb2-8c27-de7ef0542551.png)

$ sanjuuni --width=210 --height=147 -i "rick.mkv" --websocket=3355

![Screenshot_20221109_204717](https://user-images.githubusercontent.com/49335821/200926734-aa98970e-1823-4d9b-8bbe-60a035f53d1a.png)

**Comment by MCJack123** [comment]
Fixed in c64f8725a9f24dec656819923457717dfb964515
