### ISSUE TITLE
rawmode header two times

### ISSUE THREAD

**Issue by Commandcracker** [MCJack123/sanjuuni#8]
![Screenshot_20221113_123326](https://user-images.githubusercontent.com/49335821/201519546-c029ad56-df9d-4b51-8a52-414ab0e1d7ee.png)

**Comment by Apethesis** [comment]
so
what is this meant to be
you just put an image there and said nothing

**Comment by Commandcracker** [comment]
the header is two times in the file, winch berks the player
```
32Vid 1.1
12.5
```
